Newton_Raphson: main.o Newton_Raphson.o
	gcc main.o Newton_Raphson.o -o Newton_Raphson

main.o: main.c
	gcc -c main.c

Newton_Raphson.o: Newton_Raphson.c
	gcc -c Newton_Raphson.c

clean:
	rm *.o Newton_Raphson